In [1]:
import numpy as np

In [3]:
w1 = [[2, 0], [4, 0]]
w2 = [[0, -2], [0, -4]]
w3 = [[2, -2], [4, -4]]

w1_np = np.array(w1)
w2_np = np.array(w2)
w3_np = np.array(w3)

In [5]:
m1 = np.mean(w1_np, axis=0)
m2 = np.mean(w2_np, axis=0)
m3 = np.mean(w3_np, axis=0)
print('m1', m1)
print('m2', m2)
print('m3', m3)

m1 [3. 0.]
m2 [ 0. -3.]
m3 [ 3. -3.]


In [6]:
s1 = w1_np - np.ones(w1_np.shape) * m1
S1 = np.matmul(s1.T, s1)
S1

array([[2., 0.],
       [0., 0.]])

In [7]:
s2 = w2_np - np.ones(w2_np.shape) * m2
S2 = np.matmul(s2.T, s2)
S2

array([[0., 0.],
       [0., 2.]])

In [8]:
s3 = w3_np - np.ones(w3_np.shape) * m3
S3 = np.matmul(s3.T, s3)
S3

array([[ 2., -2.],
       [-2.,  2.]])

In [9]:
Sw = S1 + S2 + S3
Sw

array([[ 4., -2.],
       [-2.,  4.]])

In [15]:
m = (m1 * len(w1) + m2 * len(w2) + m3 * len(w3))/ (len(w1 + w2 + w3))
m = m.reshape(1, 2)

In [20]:
Sb = (len(w1) * np.matmul((m1 - m).T, (m1 - m)) + len(w2) * np.matmul((m2 - m).T, m2 - m) + len(w3) * np.matmul((m3 - m).T, m3 - m))
Sb

array([[12.,  6.],
       [ 6., 12.]])

In [21]:
lmbda = 9
Sb - lmbda * Sw

array([[-24.,  24.],
       [ 24., -24.]])